
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zanis
 */
public class RegisterPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterFrame
     */
    public RegisterPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_regName = new javax.swing.JTextField("");
        txt_regFamily = new javax.swing.JTextField("");
        txt_RegNcode = new javax.swing.JTextField("");
        txt_regBdate = new javax.swing.JTextField("");
        txt_regEntryDate = new javax.swing.JTextField("");
        btn_reg = new javax.swing.JButton();
        combo_FieldID = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(123, 229, 215));

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("بازگشت به منو ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Uni1.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("‌  Programming by : M.Taghizadeh");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setText(" اطلاعات مورد نیاز برای ثبت نام  را وارد کنیم");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reg1.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setText("نام");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setText("کد ملی");

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel7.setText("سال ورود ");

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel9.setText("نام خانوادگی");

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel10.setText("تاریخ تولد");

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel11.setText("رشته ی تحصیلی");

        txt_regName.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        txt_regFamily.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        txt_RegNcode.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        txt_regBdate.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        txt_regEntryDate.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        btn_reg.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_reg.setText("تایید ثبت نام و دریافت شماره دانشجویی");
        btn_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regActionPerformed(evt);
            }
        });

        combo_FieldID.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        combo_FieldID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "مهندسی کامپیوتر", "مهندسی عمران", "مهندسی صنایع", "علوم مهندسی" }));
        combo_FieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_FieldIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_regBdate, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_regFamily, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_regEntryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_RegNcode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_regName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(combo_FieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_reg)
                .addGap(245, 245, 245))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_regName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(txt_regFamily, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(txt_regBdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_RegNcode, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7)
                    .addComponent(combo_FieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_regEntryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(btn_reg)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        UniversityOfGuilan.main();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regActionPerformed
        System.out.println(txt_RegNcode.getText());
        int check = 0;
        
        if(txt_RegNcode.getText().equals("")||txt_regBdate.getText().equals("")||
           txt_regEntryDate.getText().equals("")||txt_regFamily.getText().equals("")||
           txt_regName.getText().equals("")){
            
            check=1;
            JOptionPane.showMessageDialog(null, "لطفا تمامی فیلد هارا پر کنید.");
            
        }
        else if( txt_regName.getText().contains("0")||txt_regName.getText().contains("1")||txt_regName.getText().contains("2")||
            txt_regName.getText().contains("3")||txt_regName.getText().contains("4")||txt_regName.getText().contains("5")||
            txt_regName.getText().contains("6")||txt_regName.getText().contains("7")||txt_regName.getText().contains("8")||
            txt_regName.getText().contains("9")){
            
            check=1;
            JOptionPane.showMessageDialog(null, "نام وارد شده صحیح نیست");
        }
        else if(txt_regFamily.getText().contains("0")||txt_regFamily.getText().contains("1")||txt_regFamily.getText().contains("2")||
                txt_regFamily.getText().contains("3")||txt_regFamily.getText().contains("4")||txt_regFamily.getText().contains("5")||
                txt_regFamily.getText().contains("6")||txt_regFamily.getText().contains("7")||txt_regFamily.getText().contains("8")||
                txt_regFamily.getText().contains("9")){
                check=1;
                JOptionPane.showMessageDialog(null, "نام خانوادگی صحیح نیست");
        }
        
        else if(txt_RegNcode.getText().length()!=10 || !txt_RegNcode.getText().matches("^[0-9]*$")){
            check=1;
            JOptionPane.showMessageDialog(null, "کد ملی صحیح نیست");
        }
        else if(txt_regBdate.getText().length()!=4|| !txt_regBdate.getText().matches("^[0-9]*$")||
                Integer.valueOf(txt_regBdate.getText())>1390 || Integer.valueOf(txt_regBdate.getText())<1300){
            
            check=1;
            JOptionPane.showMessageDialog(null, "تاریخ تولد وارد شده صحیح نیست محدوده ی مجاز [1300-1390]");
        }
        
        else if(txt_regEntryDate.getText().length()!=4|| !txt_regEntryDate.getText().matches("^[0-9]*$")||
                Integer.valueOf(txt_regEntryDate.getText())>1400 || Integer.valueOf(txt_regEntryDate.getText())<1300){
            
            check=1;
            JOptionPane.showMessageDialog(null, "تاریخ ورود صحیح نیست . محدوده ی مجاز [1300-1400]");
        }
        
        if(check == 0){
            try{
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = "jdbc:sqlserver://DESKTOP-8G9EST6:1433;databaseName=DB_IMP_PROJECT";
                String userName = "sa";
                String pass = "mohammad98";
                Connection connect = DriverManager.getConnection(url, userName, pass);
                Statement state=connect.createStatement();

                String FieldName = String.valueOf(combo_FieldID.getSelectedItem());
                String FieldID = "";
                if(FieldName == "مهندسی کامپیوتر"){
                    FieldID = "1";
                }
                else if(FieldName == "مهندسی عمران"){
                    FieldID = "2";
                }
                else if(FieldName == "مهندسی صنایع"){
                    FieldID = "3";
                }
                else if(FieldName == "علوم مهندسی"){
                    FieldID = "4";
                }
                String query="EXEC SP_registerINS @Name = '"+txt_regName.getText()+"', "+
                                                 "@Family = '"+txt_regFamily.getText()+"', "+
                                                 "@Ncode = '"+txt_RegNcode.getText()+"', "+
                                                 "@Bdate = '"+txt_regBdate.getText()+"', "+
                                                 "@Entrydate = '"+txt_regEntryDate.getText()+"', "+
                                                 "@FieldID = " +FieldID;
                state.execute(query);

                state.close();
                connect.close();

                txt_regName.setText("");
                txt_regFamily.setText("");
                txt_RegNcode.setText("");
                txt_regBdate.setText("");
                txt_regEntryDate.setText("");
                
                JOptionPane.showMessageDialog(null, "دانشجوی مورد نظر با موفقیت ثبت نام شد.");
            }
            catch(Exception e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "دوباره امتحان كنيد");
            }
        }
    }//GEN-LAST:event_btn_regActionPerformed

    private void combo_FieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_FieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_FieldIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_reg;
    private javax.swing.JComboBox combo_FieldID;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_RegNcode;
    private javax.swing.JTextField txt_regBdate;
    private javax.swing.JTextField txt_regEntryDate;
    private javax.swing.JTextField txt_regFamily;
    private javax.swing.JTextField txt_regName;
    // End of variables declaration//GEN-END:variables
}
